name: Deploy to AWS Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: true
        type: string
        default: 'Fix'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend
        run: echo "deploying..."
